<a href="https://colab.research.google.com/github/sebekpro/python-krakowiak/blob/main/250-data-science-bootcamp-w-jezyku-python/001_010_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 1](#1)
* [Ćwiczenie 2](#2)
* [Ćwiczenie 3](#3)
* [Ćwiczenie 4](#4)
* [Ćwiczenie 5](#5)
* [Ćwiczenie 6](#6)
* [Ćwiczenie 7](#7)
* [Ćwiczenie 8](#8)
* [Ćwiczenie 9](#9)
* [Ćwiczenie 10](#10)

### <a name='0'></a>Import biblioteki

In [5]:
import numpy as np

np.__version__

'1.26.4'

### <a name='1'></a> Ćwiczenie 1
Sprawdź czy wszystkie elementy tablic $A, B, C$ oraz $D$ zwracają wartość logiczną _True_.



```
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])
```



__Wskazówka:__ Użyj funkcji _np.all()._

In [28]:
# tutaj wpisz rozwiązanie
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])

for name, array in zip(list('ABCD'), [A, B, C, D]):
  print(f'{name}, {np.all(array)}')

A, True
B, False
C, False
D, True


### <a name='2'></a> Ćwiczenie 2
Sprawdź czy wszystkie elementy tablic $A, B$ oraz $C$ zwracają wartość logiczną _True_ wzdłuż osi z indeksem 1.


```
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])
```



__Wskazówka:__ Użyj funkcji _np.all()_ z parametrem _axis._

In [29]:
# tutaj wpisz rozwiązanie
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

a = np.all(A, axis = 1)
b = np.all(B, axis = 1)
c = np.all(C, axis = 1)

print("Wynik A = ", a)
print("Wynik B = ", b)
print("Wynik C = ", c)

for name, array in zip(list('ABC'), [A, B, C]):
  print(f'{name}, {np.all(array, axis = 1)}')

Wynik A =  [ True  True]
Wynik B =  [ True False]
Wynik C =  [False  True]
A, [ True  True]
B, [ True False]
C, [False  True]


### <a name='3'></a> Ćwiczenie 3
Sprawdź czy jakikolwiek element tablic $A, B, C$ oraz $D$ odpowiednio, zwraca wartość logiczną _True_.


```
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])
```


__Wskazówka:__ Użyj funkcji _np.any()._

In [30]:
# tutaj wpisz rozwiązanie
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

a = np.any(A)
b = np.any(B)
c = np.any(C)
d = np.any(D)

print(f"A: {a}")
print(f"B: {b}")
print(f"C: {c}")
print(f"D: {d}")

for name, array in zip(list('ABCD'), [A, B, C, D]):
  print(f'{name}, {np.any(array)}')

A: False
B: True
C: True
D: True
A, False
B, True
C, True
D, True


### <a name='4'></a> Ćwiczenie 4
Sprawdź czy jakikolwiek element tablic $A, B, C$ oraz $D$ odpowiednio, zwraca wartość logiczną _True_ wzdłuż osi z indeksem 0.


```
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])
```



__Wskazówka:__ Użyj funkcji _np.any()_ z parametrem _axis._

In [31]:
# tutaj wpisz rozwiązanie
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

a = np.any(A, axis = 0)
b = np.any(B, axis = 0)
c = np.any(C, axis = 0)
d = np.any(D, axis = 0)

print("Wynik A = ", a)
print("Wynik B = ", b)
print("Wynik C = ", c)
print("Wynik D = ", d)

for name, array in zip(list('ABCD'), [A, B, C, D]):
  print(f'{name}, {np.any(array, axis = 0)}')

Wynik A =  [False False False]
Wynik B =  [False  True False]
Wynik C =  [ True False False]
Wynik D =  [ True False]
A, [False False False]
B, [False  True False]
C, [ True False False]
D, [ True False]


### <a name='5'></a> Ćwiczenie 5
Sprawdź tablicę $A$ pod kątem braków danych (_np.nan_).


```
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])
```


__Wskazówka:__ Użyj funkcji _np.isnan()_.

In [18]:
# tutaj wpisz rozwiązanie
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])
print(f"{np.isnan(A)}")

any_nan = np.isnan(A).any()
print("Czy w tablicy A występuje choć jeden nan?:", any_nan)

[[False False False  True]
 [False  True False False]]
Czy w tablicy A występuje choć jeden nan?: True


### <a name='6'></a> Ćwiczenie 6
Sprawdź, czy poniższe tablice $A$ oraz $B$ są równe pod względem elementów (element-wise) z ustalonym poziomem tolerancji. Użyj funkcji _np.allclose()_ z domyślnymi parametrami.



```
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])
```


In [10]:
# tutaj wpisz rozwiązanie
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])

print("np.allclose(A, B) = ",np.allclose(A, B))

# sprawdzenie element po elemencie
print("np.all(np.isclose(A, B)) = ", np.all(np.isclose(A, B)))

np.allclose(A, B) =  True
np.all(np.isclose(A, B)) =  True


### <a name='7'></a> Ćwiczenie 7
Sprawdź, czy poniższe tablice $A$ oraz $B$ są równe pod względem elementów (element-wise). Użyj operatora porównania _==_.


```
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])
```

In [32]:
# tutaj wpisz rozwiązanie
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])
comparison = (A == B)
print("A == B : ", comparison)
print("np.equal(A, B) : ", np.equal(A, B))


A == B :  [False False  True]
np.equal(A, B) :  [False False  True]


### <a name='8'></a> Ćwiczenie 8
Sprawdź, dla których elementów (element-wise) poniższa tablica $A$ ma większe wartości niż tablica $B$.


```
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])
```



In [17]:
# tutaj wpisz rozwiązanie
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])
comparison = (A > B)
print("comparison = (A > B) : ", comparison)

print("np.greater(A, B) – analogiczne do A > B : ", np.greater(A, B))
print("np.less(A, B) – analogiczne do A < B : ", np.less(A, B))
indices = np.where(A > B)
print(indices)

max_vals = np.maximum(A, B)
print(max_vals)

diff = A - B
print(diff)

comparison = (A > B) :  [ True False False False]
np.greater(A, B) – analogiczne do A > B :  [ True False False False]
np.less(A, B) – analogiczne do A < B :  [False  True False  True]
(array([0]),)
[0.4  0.51 0.3  0.91]
[ 0.02 -0.01  0.   -0.01]


### <a name='9'></a> Ćwiczenie 9
Stwórz tablicę numpy wymiaru _4x4_ wypełnioną zerami. Ustal typ danych na _int_.

__Oczekiwany wynik:__


```
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])
```



__Wskazówka:__ Użyj funkcji _np.zeros()_.

In [19]:
# tutaj wpisz rozwiązanie
A = np.zeros((4,4), dtype = int)
print(A)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### <a name='10'></a> Ćwiczenie 10
Stwórz tablicę numpy wymiaru _10x10_ wypełnioną liczbą 255. Ustal typ danych na _float_.

__Oczekiwany wynik:__


```
array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])
```



__Wskazówka:__ Użyj funkcji _np.ones()_ lub _np.full()_.

In [27]:
# tutaj wpisz rozwiązanie
A = np.full((10, 10), 255, dtype = float)
B = np.ones((10, 10), dtype = float) * 255

print("A = ", A)
print("B = ", B)


A =  [[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]]
B =  [[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255