<a href="https://colab.research.google.com/github/sebekpro/python-krakowiak/blob/main/250-data-science-bootcamp-w-jezyku-python/021_030_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 21](#1)
* [Ćwiczenie 22](#2)
* [Ćwiczenie 23](#3)
* [Ćwiczenie 24](#4)
* [Ćwiczenie 25](#5)
* [Ćwiczenie 26](#6)
* [Ćwiczenie 27](#7)
* [Ćwiczenie 28](#8)
* [Ćwiczenie 29](#9)
* [Ćwiczenie 30](#10)

### <a name='0'></a>Import biblioteki

In [3]:
import numpy as np

np.__version__

'1.26.4'

### <a name='1'></a> Ćwiczenie 21
Wygeneruj poniższą tablicę numpy. Zapisz tablicę do pliku bianarnego o nazwie _'array.npy'_ i następnie wczytaj z powrotem ten plik do innej zmiennej.


```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```


__Wskazówka:__ Użyj funkcji _np.save()_ oraz _np.load()_.

In [25]:
# tutaj wpisz rozwiązanie
A = np.arange(12).reshape(3, 4)
print(f"A = \n {A}")
np.save('array.npy', A)
B = np.load('array.npy')
print(f"B = \n {B}")

A = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
B = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

### <a name='2'></a> Ćwiczenie 22
Wygeneruj ponizszą tablicę numpy:


```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```


Zapisz tablicę do pliku tekstowego o nazwie _'array.txt'_ z dokładnością do drugiego miejsca po przecinku i następnie wczytaj z powrotem ten plik do innej zmiennej.

__Wskazówka:__ Użyj funkcji _np.savetxt()_ oraz _np.loadtxt()_.


In [27]:
# tutaj wpisz rozwiązanie
A = np.arange(12).reshape(3, 4)
print(f"A = \n {A}")
np.savetxt(fname='array.txt', X=A, fmt='%0.2f')
B = np.loadtxt(fname='array.txt')
print(f"B = \n {B}")

A = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
B = 
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


### <a name='3'></a> Ćwiczenie 23
Wygeneruj i przekształć poniższą tablicę numpy na listę.


```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```



__Wskazówka:__ Użyj metody _np.array.tolist()_.

In [24]:
# tutaj wpisz rozwiązanie
A = np.arange(12).reshape(3, 4)
print(A)
print("\n")
list1 = np.array(A).tolist()
print(list1)
print("\n")


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]




### <a name='4'></a> Ćwiczenie 24
Podana jest poniższa tablica numpy:

```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```
Używając operatora wycinania przekształć tablicę w poniższe:

* zamiana wierszy (pierwszy z ostatnim)

```
array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])
```







In [17]:
# tutaj wpisz rozwiązanie
A = np.arange(12).reshape(3, 4)
print(f"A \n {A}")

a_swapped = A[::-1]
print(f"a_swapped =\n {a_swapped}")

A 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a_swapped =
 [[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


#  Składnia slicing dla jednej osi
Ogólna składnia wycinania dla listy lub tablicy wygląda tak:



```
python

[start:stop:step]
```

* **start** – indeks, od którego zaczynamy wycinanie (domyślnie początek).
* **stop** – indeks, na którym kończymy (domyślnie koniec).
* **step** – krok, czyli co ile elementów wybieramy.

Jeżeli pominiemy **start** i **stop** oraz podamy tylko step równy -1, zapisujemy to jako [::-1]. Oznacza to: „przejdź przez całą sekwencję, ale z krokiem -1”, czyli odwróć kolejność elementów.

# Jak działa a[::-1, ::-1]?
1. a[::-1] – ten fragment odnosi się do pierwszej osi tablicy (wierszy).
* Zapis [::-1] oznacza, że dla osi wierszy wybieramy wszystkie wiersze, ale zaczynając od ostatniego i idąc wstecz do pierwszego. Innymi słowy, odwracamy kolejność wierszy.

2. a[:, ::-1] – analogicznie, ten zapis odnosi się do drugiej osi tablicy (kolumn).
* Dwukropek przed przecinkiem (:) oznacza, że wybieramy wszystkie wiersze (bez zmiany kolejności), natomiast [::-1] po przecinku odwraca kolejność kolumn w każdym wierszu.

3. Łącząc oba zapisy w a[::-1, ::-1] otrzymujemy:
* Najpierw odwracamy kolejność wierszy.
* Następnie w każdej z odwróconych kolejności wierszy odwracamy kolejność kolumn.

# Dlaczego "dwa razy dwukropek"?
* Pierwszy dwukropek ([::-1]): dotyczy pierwszej osi (wierszy).
* Drugi dwukropek ([::-1]): dotyczy drugiej osi (kolumn).

W tablicach wielowymiarowych, po przecinku podajemy oddzielne wyrażenia dla każdej osi. Dzięki temu możemy niezależnie kontrolować wycinanie (slicing) dla wierszy i kolumn.


## Przykład
Rozważmy tablicę:


```
import numpy as np

a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
```
* a[::-1] daje:


```
[[ 8,  9, 10, 11],
 [ 4,  5,  6,  7],
 [ 0,  1,  2,  3]]
```
* a[:, ::-1] da (odwracamy kolumny, wiersze pozostają takie same):

```
[[ 3,  2,  1,  0],
 [ 7,  6,  5,  4],
 [11, 10,  9,  8]]

```

* a[::-1, ::-1] łączy obie operacje – odwraca kolejność wierszy i kolumn:


```
[[11, 10,  9,  8],
 [ 7,  6,  5,  4],
 [ 3,  2,  1,  0]]
```





* zamiana kolumn (odwrócona kolejność)


```
array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])
```


In [19]:
# tutaj wpisz rozwiązanie
A = np.arange(12).reshape(3, 4)
a = A[:, ::-1]

print(f"a = \n {a}")

a = 
 [[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]


* zamiana wierszy i kolumn (odwrócone kolejności)


```
array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])
```       

In [21]:
# tutaj wpisz rozwiązanie
A = np.arange(12).reshape(3, 4)
print(f"aoryginalna A = \n {A}")

a = A[::-1, ::-1]

print(f"a = \n {a}")

aoryginalna A = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a = 
 [[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


### <a name='5'></a> Ćwiczenie 25
Podaną poniżej tablicę numpy:

```
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])
```
Przekształć na tablicę:


```
array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])
```
__Wskazówka:__ Użyj funkcji _np.pad()_.





In [31]:
# tutaj wpisz rozwiązanie
a = np.ones((4, 4))

pad1 = np.pad(a, pad_width=1, mode = 'constant', constant_values = 0)
print(f"padding : \n {pad1}")

padding : 
 [[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


Funkcja np.pad() umożliwia dodawanie "obrzeży" (paddingu) do tablicy. Aby przekształcić tablicę 4×4 w tablicę 6×6 z zerowym obramowaniem, możesz użyć następującego kodu:

## Wyjaśnienie:

* np.ones((4, 4)) – tworzy tablicę 4×4 wypełnioną jedynkami.
* np.pad(a, pad_width=1, mode='constant', constant_values=0) – dodaje padding o szerokości 1 elementu na każdej krawędzi tablicy:
* pad_width=1 oznacza, że do każdej osi dodamy jeden element zarówno na
początku, jak i na końcu (jest to równoważne zapisie pad_width=((1, 1), (1, 1))).
* mode='constant' ustawia tryb wypełniania stałą wartością.
* constant_values=0 wskazuje, że wypełnienie ma odbywać się wartością 0.

### <a name='6'></a> Ćwiczenie 26
Podaną poniżej tablicę numpy:

```
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])
```
Przekształć na tablicę:


```
array([[10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0]])
```
__Wskazówka:__ Użyj operatora wycinania oraz przypisz odpowiednie wartości.





In [35]:
# tutaj wpisz rozwiązanie
# Tworzymy tablicę 6x6 wypełnioną zerami
A = np.zeros((6, 6), dtype=int)
print(A)
print("\n")

# Dla wierszy parzystych (indeksy 0, 2, 4) i kolumn parzystych (indeksy 0, 2, 4) przypisujemy wartość 10
A[::2, ::2] = 10
print(A)
print("\n")

# Dla wierszy nieparzystych (indeksy 1, 3, 5) i kolumn parzystych (indeksy 0, 2, 4) przypisujemy wartość 5
A[1::2, ::2] = 5

print(A)
print("\n")


[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


[[10  0 10  0 10  0]
 [ 0  0  0  0  0  0]
 [10  0 10  0 10  0]
 [ 0  0  0  0  0  0]
 [10  0 10  0 10  0]
 [ 0  0  0  0  0  0]]


[[10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]]




Możesz to osiągnąć, przypisując wartości do odpowiednich fragmentów tablicy przy użyciu operatora wycinania (slicing). Poniższy kod tworzy tablicę 6×6 wypełnioną zerami, a następnie:

* Wierszom o indeksach parzystych (0, 2, 4) i kolumnom o indeksach parzystych (0, 2, 4) przypisuje wartość 10.
* Wierszom o indeksach nieparzystych (1, 3, 5) i kolumnom o indeksach parzystych (0, 2, 4) przypisuje wartość 5.

## Wyjaśnienie slicing:

1. A[0::2, 0::2] oznacza:

* Dla pierwszej osi (wierszy): zaczynamy od indeksu 0 i wybieramy co drugi wiersz (czyli 0, 2, 4).
*Dla drugiej osi (kolumn): zaczynamy od indeksu 0 i wybieramy co drugą kolumnę (czyli 0, 2, 4).

2. Analogicznie, A[1::2, 0::2] wybiera:

* Wiersze o indeksach 1, 3, 5.
* Kolumny o indeksach 0, 2, 4.

### <a name='7'></a> Ćwiczenie 27
Połącz podane poniżej tablice $A$ oraz $B$ w jedną.


```
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])
```




__Oczekiwany rezultat:__


```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 4,  3,  7,  2],
       [ 0,  5,  2,  6]])
```
__Wskazówka:__ Użyj funkcji _np.append()_.


In [33]:
# tutaj wpisz rozwiązanie
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])
C = np.append(A, B, axis = 0)
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 4,  3,  7,  2],
       [ 0,  5,  2,  6]])

### <a name='8'></a> Ćwiczenie 28
Z podanych poniżej tablic $A$ i $B$ wydobądź elementy wspólne (przecięcie) tablic.

```
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])      
```



__Wskazówka:__ Użyj funkcji _np.intersect1d()_.

In [5]:
# tutaj wpisz rozwiązanie
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])

print(f"A = \n {A}")
print("\n")

print(f"B = \n {B}")
print("\n")

# Funkcja np.intersect1d(A, B) przeszukuje obie tablice (w sensie "element-wise",
# po spłaszczeniu) i zwraca unikalne elementy występujące zarówno w A, jak i w B
common_elements = np.intersect1d(A, B)
print(common_elements)

A = 
 [[0 1 2 3]
 [4 5 6 7]]


B = 
 [[ 9 10 11  3]
 [ 2  8  0  9]]


[0 2 3]


### <a name='9'></a> Ćwiczenie 29
Podana jest poniższa tablica numpy $A$.
Znajdź unikalne wartości tej tablicy.


```
A = np.array([[5, 1, 2, 1, 2],
              [9, 1, 9, 7, 5],
              [4, 1, 5, 7, 9]])
```


__Wskazówka:__ Użyj funkcji _np.unique()_.

In [11]:
# tutaj wpisz rozwiązanie
A = np.array([[5, 1, 2, 1, 2],
              [9, 1, 9, 7, 5],
              [4, 1, 5, 7, 9]])
np.unique(A)

array([1, 2, 4, 5, 7, 9])

### <a name='10'></a> Ćwiczenie 30
Podana jest poniższa tablica:


```
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])
```



Zwróć indeksy na których stoją maksymalne wartości dla danego wiersza.

__Wskazówka:__ Użyj funkcji _np.argmax()_.

In [23]:
# tutaj wpisz rozwiązanie
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])

max_indices = np.argmax(A, axis=1)
print("Indeksy maksymalnych wartości:", max_indices)
print("\n")

# Aby wyciągnąć maksymalne wartości dla każdego wiersza,
# tworzymy tablicę indeksów wierszy:
row_indices = np.arange(A.shape[0])
print("tablica indeksów wierszy:", row_indices)
print("\n")

# Następnie wykorzystujemy zaawansowane indeksowanie:
max_values = A[row_indices, max_indices]
print("Maksymalne wartości:", max_values)
print("\n")


Indeksy maksymalnych wartości: [0 2 1]


tablica indeksów wierszy: [0 1 2]


Maksymalne wartości: [0.4 0.8 0.5]


