<a href="https://colab.research.google.com/github/sebekpro/python-krakowiak/blob/main/250-data-science-bootcamp-w-jezyku-python/051_060_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 51](#1)
* [Ćwiczenie 52](#2)
* [Ćwiczenie 53](#3)
* [Ćwiczenie 54](#4)
* [Ćwiczenie 55](#5)
* [Ćwiczenie 56](#6)
* [Ćwiczenie 57](#7)
* [Ćwiczenie 58](#8)
* [Ćwiczenie 59](#9)
* [Ćwiczenie 60](#10)

### <a name='0'></a>Import biblioteki

In [2]:
import numpy as np

np.random.seed(42)
np.__version__

'1.26.4'

### <a name='1'></a> Ćwiczenie 51
Podane są poniżej dwie tablice $A$ i $B$:


```
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
```
* Połącz te tablice w następujący sposób:


```
array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.concatenate()_.





In [3]:
# tutaj wpisz rozwiązanie
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
C = np.concatenate((A, B), axis=0)
C

array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])

* Połącz te tablice w następujący sposób:


```
array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.concatenate()_.

In [4]:
# tutaj wpisz rozwiązanie
C = np.concatenate((A, B), axis = 1)
C

array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])

### <a name='2'></a> Ćwiczenie 52
Podana jest tablica zawierająca dane _data_ oraz tablica zawierająca docelową klasę dla danego wiersza _target_:

```
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
```



Połącz te tablice w jedną tak jak pokazano poniżej:


```
array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])
```



In [5]:
# tutaj wpisz rozwiązanie
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
C = np.concatenate((data, target), axis = -1)
C

array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])

### <a name='3'></a> Ćwiczenie 53
Podane są trzy poniższe jednowymiarowe tablice:  


```
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
```
Przekształć każdą z tych tablic w kolumnę i sklej w jedną dużą tablicę.

__Oczekiwany wynik:__


```
array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])
```

__Wskazówka:__ Wykorzystaj funkcję _np.column_stack()_.



In [6]:
# tutaj wpisz rozwiązanie
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
C = np.column_stack((feature1, feature2, feature3))
C

array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])

### <a name='4'></a> Ćwiczenie 54
Podana jest poniższa dwuwymiarowa tablica:

```
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A
```
```
array([[0, 0, 4, 6, 2, 4, 1, 1],
       [0, 0, 6, 2, 2, 4, 1, 1],
       [0, 0, 1, 3, 5, 5, 1, 1],
       [0, 0, 3, 1, 5, 4, 1, 1],
       [0, 0, 2, 6, 1, 3, 1, 1]])
```

Podziel tablicę na 3 części tak aby pierwsze dwie kolumny stanowiły pierwszą tablicę $A1$, cztery kolejne drugą tablicę $A2$ oraz dwie ostatnie trzecią tablicę $A3$.

__Wskazówka:__ Wykorzystaj funkcję _np.split()_.

In [7]:
# tutaj wpisz rozwiązanie
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A

array([[0, 0, 4, 6, 2, 4, 1, 1],
       [0, 0, 6, 2, 2, 4, 1, 1],
       [0, 0, 1, 3, 5, 5, 1, 1],
       [0, 0, 3, 1, 5, 4, 1, 1],
       [0, 0, 2, 6, 1, 3, 1, 1]])

In [20]:
# Pierwsza metoda
A1, A2, A3 = np.split(A, [2, 6], axis = 1)
print(f"A1: \n{A1}\n")
print(f"A2: \n{A2}\n")
print(f"A3: \n{A3}\n")

# Druga metoda
B1 = A[:, :2]
B2 = A[:, 2:6]
B3 = A[:, -2:]
print(f"B1: \n{B1}\n")
print(f"B2: \n{B2}\n")
print(f"B3: \n{B3}\n")


A1: 
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]

A2: 
[[4 6 2 4]
 [6 2 2 4]
 [1 3 5 5]
 [3 1 5 4]
 [2 6 1 3]]

A3: 
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]

B1: 
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]

B2: 
[[4 6 2 4]
 [6 2 2 4]
 [1 3 5 5]
 [3 1 5 4]
 [2 6 1 3]]

B3: 
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]



### <a name='5'></a> Ćwiczenie 55
Podana jest poniższa tablica $A$:

```
A = np.random.randint(low=0, high=2, size=(10, 6))
```
Wyznacz łączną liczbę elementów niezerowych dla tej tablicy.

__Wskazówka:__ Wykorzystaj funkcję _np.count_nonzero()_.


In [24]:
# tutaj wpisz rozwiązanie
A = np.random.randint(low=0, high=2, size=(10, 6))
non_zero = np.count_nonzero(A)
print(f"A = \n {A} \n")
non_zero

A = 
 [[0 0 1 1 1 1]
 [1 1 1 1 0 1]
 [1 0 1 0 0 1]
 [0 0 0 0 1 0]
 [1 0 0 0 0 1]
 [1 0 0 1 0 0]
 [0 1 1 1 0 0]
 [1 1 1 1 0 1]
 [0 1 0 1 1 1]
 [1 0 1 0 0 0]] 



31

Wyznacz łączną liczbę elementów niezerowych dla każdego wiersza tej tablicy.

__Wskazówka:__ Wykorzystaj funkcję _np.count_nonzero()_.

In [26]:
# tutaj wpisz rozwiązanie
non_zero_rows = np.count_nonzero(A, axis = 1)
non_zero_rows

array([4, 5, 3, 1, 2, 2, 3, 5, 4, 2])

### <a name='6'></a> Ćwiczenie 56
Poniżej podana jest przykładowa tablica $A$:

```
A = np.random.randn(10, 4)
```

```
array([[-0.53441645, -1.49505387, -0.78925833,  0.74371128],
       [-0.21216142, -0.42686879,  0.50144833,  1.15818665],
       [ 0.25711687,  0.3145129 ,  1.37186213,  0.17555329],
       [-0.30928855,  0.6731255 , -0.25663018, -0.36782572],
       [ 1.27373362, -0.29195267, -2.65517605,  0.34551794],
       [-0.39551645, -0.28913686,  0.45293633, -0.16606091],
       [ 0.21493883, -2.02231493, -0.94305681,  1.40395874],
       [-0.0185508 , -1.67350462, -1.07253183, -0.99258618],
       [ 0.10234768, -0.43260928, -0.6591823 ,  0.0039373 ],
       [ 0.4777541 , -0.25902864, -0.57470921, -0.42149822]])
```


Ustaw odopowiednią opcję biblioteki numpy pozwalającą drukować tablice z określoną precyzją. Ustaw jej wartość na 4 i wydrukuj tablicę $A$.



In [38]:
# tutaj wpisz rozwiązanie
np.set_printoptions(precision = 4)
A = np.random.randn(10, 4)
A

array([[ 1.1678,  0.2544,  0.3376, -0.4119],
       [-0.4876, -0.4326,  0.3945, -0.421 ],
       [ 0.2898,  2.0754,  0.8711, -0.326 ],
       [ 1.2012, -0.4081, -2.0381, -1.0081],
       [-1.8708, -0.3515,  0.0184,  1.6764],
       [ 0.3269, -0.2191,  0.8294, -2.2111],
       [ 0.2356,  0.7709, -1.4786,  1.1438],
       [ 0.3385, -0.4153,  0.6328,  2.2707],
       [ 0.1819,  0.2482, -0.4594, -0.8498],
       [ 0.8303, -0.8561,  0.0716, -0.4777]])

### <a name='7'></a> Ćwiczenie 57
Podana jest poniższa tablica numpy $A$:

```
A = np.array([1.2e-6, 1.7e-7])
```

Ustaw wartość precyzji na 8. Następnie ustaw odopowiednią opcję biblioteki numpy pozwalającą stłumić notację wykładniczą. Wydrukuj tablicę $A$.

__Oczekiwany wynik:__


```
array([0.0000012 , 0.00000017])
```





In [54]:
# tutaj wpisz rozwiązanie
A = np.array([1.2e-6, 1.7e-7])
np.set_printoptions(precision = 8, suppress = True)
A

array([0.0000012 , 0.00000017])

### <a name='8'></a> Ćwiczenie 58
Podana jest poniższa tablica numpy $A$:

```
A = np.random.randn(8, 4)
```
Usuń trzecią kolumnę z tablicy $A$.

__Oczekiwany wynik:__


```
array([[-0.55692881, -0.66003196,  0.70856031],
       [ 0.22378737, -0.19796576, -0.16889332],
       [ 0.26062786,  0.29865445, -0.92259267],
       [-2.40317659,  1.79961876, -1.96495796],
       [ 0.13051561, -1.7085185 ,  0.54885043],
       [ 1.77268727,  0.38751181, -0.05141955],
       [-1.80858596, -0.45075211,  0.15332866],
       [ 1.94218961, -1.93679529, -1.83350954]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.delete()_.




In [58]:
# tutaj wpisz rozwiązanie
A = np.random.randn(8, 4)
print(f"A oryginal table = \n {A}")

B = np.delete(A, 2, axis = 1)
print(f"A delete 3 column = \n {B}")

A oryginal table = 
 [[ 0.71095997  0.44426331 -0.36096617  1.1593298 ]
 [-1.08106333  0.61593561  0.59310126 -0.30954644]
 [ 0.32613302 -1.25111358  0.92402702 -0.18490214]
 [-0.52272302  1.04900923 -0.70434369 -1.4084613 ]
 [-1.55662917  0.60600995 -1.28042935  1.75479418]
 [-2.08192941  1.69645637  0.21101747 -0.09671311]
 [-0.54491909  0.39913611 -0.0376347   1.10330188]
 [ 0.11422765  0.15030176 -0.36361221 -0.05694562]]
A delete 3 column = 
 [[ 0.71095997  0.44426331  1.1593298 ]
 [-1.08106333  0.61593561 -0.30954644]
 [ 0.32613302 -1.25111358 -0.18490214]
 [-0.52272302  1.04900923 -1.4084613 ]
 [-1.55662917  0.60600995  1.75479418]
 [-2.08192941  1.69645637 -0.09671311]
 [-0.54491909  0.39913611  1.10330188]
 [ 0.11422765  0.15030176 -0.05694562]]


### <a name='9'></a> Ćwiczenie 59
Podana jest tablica jednowymiarowa $v$ (wektor):

```
v = np.array([3, 4, -2])
```
Policz normę wektora $v$.


In [59]:
# tutaj wpisz rozwiązanie
v = np.array([3, 4, -2])

# v = sqrt(3^2 + 4^2 + (-2)^2) = sqrt(9 + 16 + 4) = sqrt(29), which is about 5.385.
vaector_norm = np.linalg.norm(v)
vaector_norm

5.385164807134504

### <a name='10'></a> Ćwiczenie 60
Poniżej podana jest przykładowa tablica $A$:


```
A = np.random.randint(10, size=(100, 30))
```
Ustaw odopowiednią opcję biblioteki numpy pozwalającą drukować 10 skrajnych elementów. Wydrukuj tablicę $A$.


In [61]:
# tutaj wpisz rozwiązanie
A = np.random.randint(10, size=(100, 30))
print(A)
print("\n")
np.set_printoptions(edgeitems = 10)
print(A)

[[3 8 0 ... 9 4 6]
 [9 3 0 ... 1 9 0]
 [9 1 1 ... 3 9 4]
 ...
 [9 6 9 ... 1 5 4]
 [3 6 7 ... 1 0 9]
 [2 3 4 ... 3 0 7]]


[[3 8 0 1 1 5 3 9 2 2 ... 1 7 8 3 7 8 9 9 4 6]
 [9 3 0 2 4 2 6 8 5 9 ... 9 9 5 7 7 8 7 1 9 0]
 [9 1 1 2 9 6 1 0 5 8 ... 6 4 3 6 6 5 7 3 9 4]
 [3 0 7 0 4 5 5 4 2 4 ... 1 1 7 0 5 5 3 9 2 2]
 [0 2 3 4 2 5 4 2 5 5 ... 9 2 8 3 2 1 9 8 3 2]
 [6 7 1 6 4 4 2 4 1 3 ... 7 6 4 4 6 8 8 8 5 9]
 [5 2 0 6 3 0 7 5 5 1 ... 2 7 9 1 4 0 5 1 3 5]
 [9 7 7 5 3 7 7 9 0 3 ... 3 4 9 0 6 8 7 4 3 6]
 [4 6 0 0 9 2 1 1 6 9 ... 4 8 7 7 7 7 6 7 7 7]
 [9 6 0 3 3 4 9 5 3 1 ... 7 7 2 6 0 0 6 9 8 6]
 ...
 [6 2 2 9 7 4 3 6 6 8 ... 7 4 9 6 4 7 9 9 3 1]
 [2 7 6 1 5 8 3 8 1 1 ... 3 8 0 7 4 0 3 0 5 1]
 [4 6 1 5 5 4 4 2 9 9 ... 6 4 6 3 7 9 9 6 9 4]
 [5 4 6 1 4 9 2 8 5 9 ... 4 6 5 1 3 1 0 2 2 6]
 [0 8 5 3 2 2 1 1 9 4 ... 5 0 2 9 4 9 4 9 5 9]
 [7 4 0 4 2 3 7 6 4 1 ... 6 5 4 7 2 5 4 7 3 7]
 [9 1 8 8 9 9 5 3 3 5 ... 8 8 8 7 9 2 0 7 6 4]
 [9 6 9 3 8 9 1 8 8 4 ... 5 4 1 9 9 1 6 1 5 4]
 [3 6 7 3 0 0 0 0 4 3 ... 7