<a href="https://colab.research.google.com/github/sebekpro/python-krakowiak/blob/main/250-data-science-bootcamp-w-jezyku-python/071_080_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 71](#1)
* [Ćwiczenie 72](#2)
* [Ćwiczenie 73](#3)
* [Ćwiczenie 74](#4)
* [Ćwiczenie 75](#5)
* [Ćwiczenie 76](#6)
* [Ćwiczenie 77](#7)
* [Ćwiczenie 78](#8)
* [Ćwiczenie 79](#9)
* [Ćwiczenie 80](#10)

### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np

np.random.seed(42)
np.__version__

'1.26.4'

### <a name='1'></a> Ćwiczenie 71
Podana jest poniższa tablica $A$:

```
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])
```
Od drugiego wiersza tablicy $A$ przestaw losowo wiersze w tablicy.

__Wskazówka:__ Użyj funkcji _np.random.shuffle()_.


In [2]:
# tutaj wpisz rozwiązanie
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])
np.random.shuffle(A[1:])
A

array([['id', 'price'],
       ['002', '4.99'],
       ['005', '1.49'],
       ['003', '7.99'],
       ['001', '14.99'],
       ['004', '2.49']], dtype='<U32')

### <a name='2'></a> Ćwiczenie 72
Podana jest poniższa tablica $A$:

```
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])
```
Zwróć tablicę indeksów, które posortują tablicę $A$ rosnąco.

__Oczekiwny wynik:__


```
array([5, 2, 1, 0, 4, 3])
```
__Wskazówka:__ Użyj funkcji _np.argsort()_.



In [3]:
# tutaj wpisz rozwiązanie
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])
A_sort = np.argsort(A)
A_sort

array([5, 2, 1, 0, 4, 3])

### <a name='3'></a> Ćwiczenie 73
Podana jest poniższa tablica $A$:

```
A = np.random.randn(10, 8)
```

Zaokrąglij wartości tej tablicy do trzeciego miejsca po przecinku.

__Wskazówka:__ Użyj funkcji _np.round()_.

In [5]:
# tutaj wpisz rozwiązanie
A = np.random.randn(10, 8)
A = np.round(A,3)
A

array([[ 1.794,  0.581,  0.298, -1.028, -1.419,  0.19 ,  0.136,  0.608],
       [ 0.705,  0.361, -1.467,  0.893, -0.105, -0.955, -0.415, -1.399],
       [-0.344,  0.751, -0.328, -0.862, -0.258,  0.461, -1.349, -1.019],
       [ 0.127, -1.249,  1.945, -0.153, -0.907, -0.817, -0.483, -0.57 ],
       [-2.092,  1.264, -0.015, -0.027,  0.818, -1.055, -0.758,  0.457],
       [-0.064,  0.345, -0.08 , -0.241,  1.434,  1.066, -2.499,  1.48 ],
       [ 2.159,  1.232, -0.214, -0.689,  0.728, -0.619,  0.356, -0.022],
       [ 1.218, -0.389, -0.443,  0.378,  1.934,  0.081, -0.416,  0.858],
       [ 0.718, -0.951, -0.536,  1.097,  0.428, -2.47 ,  0.482,  0.926],
       [-0.838,  0.677,  1.872,  0.396, -0.626, -0.522,  0.013,  0.378]])

### <a name='4'></a> Ćwiczenie 74
Wyznacz pierwiastki wielomianu:
* $W(x) = 4x^2 + 5x + 1$


__Wskazówka:__ Użyj funkcji _np.roots()_ oraz _np.polyval()_.

In [10]:
# tutaj wpisz rozwiązanie
polynomial = np.array([4, 5, 1])
roots = np.roots(polynomial)

print(f"Pierwiastki wielomianu W(x) = 4x^2 + 5x + 1: {roots}\n")

Pierwiastki wielomianu W(x) = 4x^2 + 5x + 1: [-1.   -0.25]



Dokonaj sprawdzenia.

In [11]:
# tutaj wpisz rozwiązanie
for r in roots:
  v = np.polyval(polynomial, r)
  print(f"W({r}) = {v}\n")

W(-1.0) = 0.0

W(-0.25) = 0.0



### <a name='5'></a> Ćwiczenie 75
Wyznacz pierwiastki wielomianów:
* $Q(x) = 2x^3 + 4x^2 -5x + 1$
* $R(x) = 2x^3 -5x + 1$

__Wskazówka:__ Użyj funkcji _np.roots()_.

In [12]:
# tutaj wpisz rozwiązanie
polynomial1 = np.array([2, 4, -5, 1])
polynomial2 = np.array([2, -5, 1])
roots1 = np.roots(polynomial1)
roots2 = np.roots(polynomial2)

print(f"Pierwiastki wielomianu W(x) = 2x^3 + 4x^2 − 5x + 1: {roots1}\n")
print(f"Pierwiastki wielomianu W(x) = 2x^3 − 5x + 1: {roots2}\n")


Pierwiastki wielomianu W(x) = 2x^3 + 4x^2 − 5x + 1: [-2.91610583  0.65388685  0.26221898]

Pierwiastki wielomianu W(x) = 2x^3 − 5x + 1: [2.28077641 0.21922359]



In [16]:
for r in roots1:
  v = np.polyval(polynomial, r)
  print(f"W({r}) = {v}\n")

W(-2.916105827293624) = 20.43416364743521

W(0.6538868491936156) = 5.979706292161495

W(0.2622189781000103) = 2.586130060403306



### <a name='6'></a> Ćwiczenie 76
Podane są wielomiany:

* $W(x) = 4x^2 + 5x + 1$
* $Q(x) = 2x^3 + 4x^2 -5x + 1$


In [26]:
W = np.array([4, 5, 1])
Q = np.array([2, 4, -5, 1])

Wp = np.poly1d(W)
Qp = np.poly1d(Q)

Wykonaj działania:
* $W(x) + Q(x)$

In [27]:
# tutaj wpisz rozwiązanie
sum_poly = Wp + Qp
sum_poly

poly1d([2, 8, 0, 2])

* $W(x) - Q(x)$


In [28]:
# tutaj wpisz rozwiązanie
diff_poly = Wp - Qp
diff_poly

poly1d([-2,  0, 10,  0])

* $W(x) * Q(x)$


In [30]:
# tutaj wpisz rozwiązanie
mul = Wp * Qp
mul

poly1d([  8,  26,   2, -17,   0,   1])

* $W(x) + 2Q(x)$

In [32]:
# tutaj wpisz rozwiązanie
sum_poly = Wp + 2 * Qp
sum_poly

poly1d([ 4, 12, -5,  3])

### <a name='7'></a> Ćwiczenie 77
Podana jest poniższa tablica:

```
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])
```

Użyj funkcji znaku (_sign function_) dla tablicy $A$. Dla przypomnienia funkcja działa nastpująco: dla wartości ujemnych zwraca -1, dla zera wartość zero, dla wartości dodatnich 1.

__Oczekiwany wynik:__


```
array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])
```
__Wskazówka:__ Użyj funkcji _np.sign()_.


In [34]:
# tutaj wpisz rozwiązanie
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])
signA = np.sign(A)
signA

array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])

### <a name='8'></a> Ćwiczenie 78
Wykorzystując funkcję _np.arange()_ wygeneruj poniższą tablicę:


```
array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31'], dtype='datetime64[D]')
```



In [41]:
# tutaj wpisz rozwiązanie
from datetime import datetime
import locale

dates = np.arange('2021-01-01', '2021-02-01', dtype=np.datetime64)
print(f'dates: {dates}\n')

# dni i nazwy w danym zakresie
try:
    locale.setlocale(locale.LC_TIME, 'pl_PL.UTF-8')
except locale.Error:
    print("Lokalizacja polska nie jest dostępna, używana będzie domyślna (angielska).")

dates_family = np.arange('2025-03-01', '2025-04-01', dtype=np.datetime64)
day_names = [datetime.strptime(str(d), '%Y-%m-%d').strftime('%A') for d in dates_family]
combined = np.array(list(zip(dates_family, day_names)), dtype=object)
print(combined)

dates: ['2021-01-01' '2021-01-02' '2021-01-03' '2021-01-04' '2021-01-05'
 '2021-01-06' '2021-01-07' '2021-01-08' '2021-01-09' '2021-01-10'
 '2021-01-11' '2021-01-12' '2021-01-13' '2021-01-14' '2021-01-15'
 '2021-01-16' '2021-01-17' '2021-01-18' '2021-01-19' '2021-01-20'
 '2021-01-21' '2021-01-22' '2021-01-23' '2021-01-24' '2021-01-25'
 '2021-01-26' '2021-01-27' '2021-01-28' '2021-01-29' '2021-01-30'
 '2021-01-31']

Lokalizacja polska nie jest dostępna, używana będzie domyślna (angielska).
[[numpy.datetime64('2025-03-01') 'Saturday']
 [numpy.datetime64('2025-03-02') 'Sunday']
 [numpy.datetime64('2025-03-03') 'Monday']
 [numpy.datetime64('2025-03-04') 'Tuesday']
 [numpy.datetime64('2025-03-05') 'Wednesday']
 [numpy.datetime64('2025-03-06') 'Thursday']
 [numpy.datetime64('2025-03-07') 'Friday']
 [numpy.datetime64('2025-03-08') 'Saturday']
 [numpy.datetime64('2025-03-09') 'Sunday']
 [numpy.datetime64('2025-03-10') 'Monday']
 [numpy.datetime64('2025-03-11') 'Tuesday']
 [numpy.datetime64('20


### <a name='9'></a> Ćwiczenie 79

Wykorzystując funkcję _np.arange()_ wygeneruj poniższą tablicę:



```
array([['2021-01', '2021-02', '2021-03'],
       ['2021-04', '2021-05', '2021-06'],
       ['2021-07', '2021-08', '2021-09'],
       ['2021-10', '2021-11', '2021-12']], dtype='datetime64[M]')
```



In [53]:
# tutaj wpisz rozwiązanie
dates_2 = np.arange('2021-01', '2022-01', dtype=np.datetime64).reshape(4, 3)
dates_2

array([['2021-01', '2021-02', '2021-03'],
       ['2021-04', '2021-05', '2021-06'],
       ['2021-07', '2021-08', '2021-09'],
       ['2021-10', '2021-11', '2021-12']], dtype='datetime64[M]')

### <a name='10'></a> Ćwiczenie 80

Wykorzystując funkcję _np.datetime64()_ wygeneruj dzisiejszą datę (datę w chwili robienia ćwiczenia).

In [54]:
# tutaj wpisz rozwiązanie
print(np.datetime64('today'))

2025-02-10
