<a href="https://colab.research.google.com/github/sebekpro/python-krakowiak/blob/main/250-data-science-bootcamp-w-jezyku-python/191_200_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pandas

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 191](#1)
* [Ćwiczenie 192](#2)
* [Ćwiczenie 193](#3)
* [Ćwiczenie 194](#4)
* [Ćwiczenie 195](#5)
* [Ćwiczenie 196](#6)
* [Ćwiczenie 197](#7)
* [Ćwiczenie 198](#8)
* [Ćwiczenie 199](#9)
* [Ćwiczenie 200](#10)

### <a name='0'></a>Import biblioteki

In [ ]:
import numpy as np
import pandas as pd

np.__version__

'1.26.4'

### <a name='1'></a> Ćwiczenie 191
Z poniższego słownika _data_ utwórz obiekt _DataFrame_ i przypisz do zmiennej _df_.


```
data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}
```



In [ ]:
# tutaj wpisz rozwiązanie
data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}
df = pd.DataFrame(data)
df.head()

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

Wyświetl podstawowe informacje na temat obiektu _df_.

In [ ]:
# tutaj wpisz rozwiązanie
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 372.0+ bytes


Dokonaj konwersji zmiennych na poszczególne typy:
* size -> _category_
* color -> _category_
* gender -> _category_
* weight -> _float_
* bought -> _category_

In [ ]:
# tutaj wpisz rozwiązanie
columnNameAndType = {
'size': 'category',
    'color': 'category',
    'gender': 'category',
    'price': 'float64',  # już jest float64, ale dla kompletności
    'weight': 'float64',  # zmieniamy z int64 na float64
    'bought': 'category'}
for col, dtype in columnNameAndType.items():
  df[col] = df[col].astype(dtype)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 744.0 bytes


### <a name='2'></a> Ćwiczenie 192
Wykorzystując bibliotekę do uczenia maszynowego _scikit-learn_ oraz klasę _LabelEncoder_ dokonaj kodowania 0-1 zmiennej _bought_. Zmiany przypisz na stałe do obiektu _df_ i wyświetl ten obiekt.

In [ ]:
# tutaj wpisz rozwiązanie
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['bought'] = le.fit_transform(df['bought'])
df.head()

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

1. Inicjalizowany jest obiekt LabelEncoder jako le.
2. Metoda fit_transform() jest wywoływana na kolumnie bought z obiektu DataFrame. Funkcja ta:
* Dopasowuje (fit) etykiety występujące w kolumnie do wewnętrznej reprezentacji numerycznej.
* Następnie przekształca (transform) oryginalne wartości (tekstowe) na odpowiadające im liczby.
3. Efektem tego działania jest zamiana wartości 'yes' i 'no' na liczby (najczęściej: 'no' → 0, 'yes' → 1, chociaż kolejność może zależeć od kolejności występowania etykiet).

Wykorzystując odpowiednią metodę klasy _LabelEncoder_ przywróć pierwotną postać zmiennej _bought_. Zwróć uwagę na typ zmiennej _bought_.

In [ ]:
# tutaj wpisz rozwiązanie

# Przywracanie oryginalnych etykiet
df['bought'] = le.inverse_transform(df['bought'])

# Konwersja na typ kategoryczny
df['bought'] = df['bought'].astype('category')

df.head()

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

### <a name='3'></a> Ćwiczenie 193
Wykorzystując bibliotekę do uczenia maszynowego _scikit-learn_ oraz klasę _OneHotEncoder_ dokonaj kodowania 0-1 zmiennej _size_. Nie przypisuj zmian do obiektu _df_.

Użyj parametru _sparse=False_ klasy _OneHotEncoder_.

In [ ]:
# tutaj wpisz rozwiązanie
from sklearn.preprocessing import OneHotEncoder

# Inicjalizacja OneHotEncoder z parametrem sparse=False
ohe = OneHotEncoder(sparse_output=False)

# Kodowanie kolumny 'size' (wynik to tablica numpy)
size_encoded = ohe.fit_transform(df[['size']])

# Wyświetlenie zakodowanej macierzy
print(size_encoded)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


1. Inicjalizacja OneHotEncoder:
Tworzymy obiekt ohe klasy OneHotEncoder z parametrem sparse=False, co zapewnia, że wynik transformacji będzie tablicą numpy, a nie macierzą rzadką.

2. Kodowanie zmiennej size:
Metoda fit_transform() jest wywoływana na kolumnie size (uwzględnionej jako DataFrame z wykorzystaniem df[['size']]). Wynik jest przypisywany do zmiennej size_encoded.

3. Wyświetlenie wyniku:
Na końcu kod wypisuje zakodowaną tablicę, która przedstawia zmienną size w postaci macierzy 0-1.

Wykorzystując bibliotekę do uczenia maszynowego _scikit-learn_ oraz klasę _OneHotEncoder_ dokonaj kodowania 0-1 zmiennej _size_. Nie przypisuj zmian do obiektu _df_.

Użyj parametru _sparse=False_ **oraz _drop=first_** klasy _OneHotEncoder_.

In [ ]:
# tutaj wpisz rozwiązanie

# Inicjalizacja OneHotEncoder z parametrami sparse=False oraz drop='first'
ohe = OneHotEncoder(sparse_output=False, drop='first')

# Kodowanie zmiennej 'size' (wynik to tablica numpy)
size_encoded = ohe.fit_transform(df[['size']])

# Wyświetlenie zakodowanej macierzy
print(size_encoded)

[[0. 1.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [1. 0.]]


1. Inicjalizacja OneHotEncoder:
Obiekt ohe jest tworzony z parametrami:

* sparse=False: zapewnia, że wynik transformacji będzie gęstą tablicą numpy.
* drop='first': powoduje, że pierwsza kategoria zostanie pominięta, co może pomóc uniknąć problemów z kolinearnością przy modelowaniu.
2. Transformacja danych:
Metoda fit_transform() jest stosowana do kolumny size (przekazanej jako DataFrame przy użyciu df[['size']]), dzięki czemu uzyskujemy macierz z zakodowanymi danymi.

3. Wynik:
Zakodowana macierz 0-1 jest zapisywana w zmiennej size_encoded, a wynik jest wyświetlany przy użyciu funkcji print().

### <a name='4'></a> Ćwiczenie 194
Wykorzystując bibliotekę _pandas_ oraz funkcję _get_dummies()_ przedstaw wszystkie zmienne kategoryczne obiektu _df_ w postaci kodowania 0-1. Nie przypisuj zmian na trwałe do obiektu _df_.

In [ ]:
# tutaj wpisz rozwiązanie

# Tworzenie DataFrame z zakodowanymi zmiennymi kategorycznymi
# Funkcja pd.get_dummies() automatycznie wykrywa kolumny typu object lub category
df_dummies = pd.get_dummies(df)

# Wyświetlenie nowego DataFrame z kodowaniem 0-1
print(df_dummies)

   price  weight  size_L  size_M  size_XL  color_blue  color_green  color_red  \
0  199.0   500.0   False   False     True       False        False       True   
1   89.0   450.0    True   False    False       False         True      False   
2   99.0   300.0   False    True    False        True        False      False   
3  129.0   380.0    True   False    False       False         True      False   
4   79.0   410.0   False    True    False       False        False       True   

   gender_female  gender_male  bought_no  bought_yes  
0           True        False      False        True  
1          False         True       True       False  
2          False         True      False        True  
3           True        False       True       False  
4           True        False      False        True  


1. Użycie funkcji get_dummies():
Wywołanie pd.get_dummies(df) generuje nowy DataFrame, w którym:
* Dla każdej zmiennej kategorycznej zostają utworzone nowe kolumny.
* Nazwa nowej kolumny składa się z oryginalnej nazwy oraz wartości danej kategorii, np. size_XL, size_L, size_M.
* Wartości 1 lub 0 wskazują obecność danej kategorii w danym wierszu.
* Kolumny numeryczne (tu: price, weight) pozostają bez zmian.

Wykorzystując bibliotekę _pandas_ oraz funkcję _get_dummies()_ przedstaw wszystkie zmienne kategoryczne obiektu _df_ w postaci kodowania 0-1. Użyj parametru _drop_first=True_. Nie przypisuj zmian na trwałe do obiektu _df_.

In [ ]:
# tutaj wpisz rozwiązanie

# Kodowanie zmiennych kategorycznych na zmienne dummy, drop_first=True
df_dummies = pd.get_dummies(df, drop_first=True)

# Wyświetlenie DataFrame z kodowaniem 0-1
print(df_dummies)

   price  weight  size_M  size_XL  color_green  color_red  gender_male  \
0  199.0   500.0   False     True        False       True        False   
1   89.0   450.0   False    False         True      False         True   
2   99.0   300.0    True    False        False      False         True   
3  129.0   380.0   False    False         True      False        False   
4   79.0   410.0    True    False        False       True        False   

   bought_yes  
0        True  
1       False  
2        True  
3       False  
4        True  


1. Funkcja pd.get_dummies() automatycznie wykrywa zmienne kategoryczne i przekształca je na zestaw kolumn z wartościami 0-1.
2. Użycie parametru drop_first=True powoduje, że dla każdej zmiennej kategorycznej pomijana jest pierwsza kategoria. Dzięki temu, gdy wszystkie pozostałe dummy mają wartość 0, wiadomo, że dana obserwacja należy do kategorii bazowej.
3. Wynik operacji jest przypisany do zmiennej df_dummies, więc oryginalny DataFrame df pozostaje bez zmian.

Wykorzystując bibliotekę _pandas_ oraz funkcję _get_dummies()_ przedstaw **zmienną _size_** obiektu _df_ w postaci kodowania 0-1. Użyj parametru _drop_first=True_. Nie przypisuj zmian na trwałe do obiektu _df_.

In [ ]:
# tutaj wpisz rozwiązanie

# Kodowanie tylko kolumny 'size' z parametrem drop_first=True
size_dummies = pd.get_dummies(df['size'], drop_first=True)

# Wyświetlenie wynikowej macierzy 0-1
print(size_dummies)

       M     XL
0  False   True
1  False  False
2   True  False
3  False  False
4   True  False


* pd.get_dummies(df['size'], drop_first=True): Funkcja ta przekształca kolumnę size w nowy DataFrame z kolumnami odpowiadającymi poszczególnym kategoriom (z pominięciem pierwszej, zgodnie z kolejnością sortowania).
* Dzięki drop_first=True, dla każdej obserwacji brak zaznaczenia w utworzonych kolumnach (czyli [0, 0]) oznacza, że dana obserwacja należy do kategorii, która została pominięta.

### <a name='5'></a> Ćwiczenie 195
Wykorzystując bibliotekę do uczenia maszynowego _scikit-learn_ oraz klasę _StandardScaler_ dokonaj skalowania zmiennej _weight_. Nie przypisuj zmian do obiektu _df_.

In [ ]:
# tutaj wpisz rozwiązanie
from sklearn.preprocessing import StandardScaler

# Inicjalizacja StandardScaler
scaler = StandardScaler()

# Skalowanie kolumny 'weight' (wynik to macierz numpy)
weight_scaled = scaler.fit_transform(df[['weight']])

# Wyświetlenie wynikowych skalowanych wartości
print(weight_scaled)

[[ 1.3660019 ]
 [ 0.62360956]
 [-1.60356745]
 [-0.41573971]
 [ 0.02969569]]


1. Inicjalizacja i skalowanie:
Tworzymy obiekt scaler klasy StandardScaler, a następnie wywołujemy metodę fit_transform() na kolumnie weight. Metoda ta dopasowuje skalowanie (oblicza średnią i odchylenie standardowe) i przekształca dane w jedną operację. Wynik jest zapisywany w zmiennej weight_scaled.

2. Wyświetlenie wyniku:
Macierz skalowanych wartości jest wypisywana przy użyciu funkcji print(). Oryginalny DataFrame df nie jest modyfikowany.

### <a name='6'></a> Ćwiczenie 196
Wczytaj raz jeszcze słownik _data_ do obiektu _DataFrame_ o nazwie _df_.

In [ ]:
# tutaj wpisz rozwiązanie

df = pd.DataFrame(data)

Przygotuj dane do modelu uczenia maszynowego:
* wykorzystując klasę LabelEncoder dokonaj kodowania 0-1 zmiennej _bought_
* dokonaj standaryzacji zmiennych _weight_ oraz _price_
* dokonaj kodowania 0-1 posoztałych zmiennych kategorycznych wykorzystując funkcję _get_dummies()._

Przypisz zmiany do zmiennej _df_prep_.

In [ ]:
# tutaj wpisz rozwiązanie

# Kodowanie zmiennej 'bought' na postać 0-1
le = LabelEncoder()
df['bought'] = le.fit_transform(df['bought'])

# Standaryzacja zmiennych 'weight' oraz 'price'
scaler = StandardScaler()
df[['weight', 'price']] = scaler.fit_transform(df[['weight', 'price']])

# Kodowanie zmiennych kategorycznych ('size', 'color', 'gender') na postać 0-1
# Używamy get_dummies() z parametrem drop_first=True, aby uniknąć pułapki zmiennych dummy.
df_prep = pd.get_dummies(df, columns=['size', 'color', 'gender'], drop_first=True)

# Wyświetlenie przygotowanych danych
print(df_prep)

      price    weight  bought  size_M  size_XL  color_green  color_red  \
0  1.845062  1.366002       1   False     True        False       True   
1 -0.691898  0.623610       0   False    False         True      False   
2 -0.461266 -1.603567       1    True    False        False      False   
3  0.230633 -0.415740       0   False    False         True      False   
4 -0.922531  0.029696       1    True    False        False       True   

   gender_male  
0        False  
1         True  
2         True  
3        False  
4        False  


* LabelEncoder: Zamienia zmienną bought (z wartościami 'yes' i 'no') na liczby (np. 'no' → 0, 'yes' → 1).
* StandardScaler: Standaryzuje zmienne weight oraz price, tj. przekształca dane tak, aby miały średnią 0 i odchylenie standardowe 1.
* pd.get_dummies() z drop_first=True: Dla pozostałych zmiennych kategorycznych (tu: size, color, gender) tworzy kolumny dummy, przy czym pomija pierwszą kategorię, aby uniknąć kolinearności.

### <a name='7'></a> Ćwiczenie 197
Skopiuj obiekt _df_prep_ do zmiennej _data_. Następnie wyrwij z tego obiektu kolumnę _bought_ i przypisz do zmiennej _target_.


In [ ]:
# tutaj wpisz rozwiązanie

# Kopiowanie df_prep do zmiennej data
data = df_prep.copy()

# Wyrwanie kolumny 'bought' i przypisanie jej do zmiennej target
target = data.pop('bought')

# Opcjonalne wyświetlenie wyników:
print(data.head())
print(target.head())

      price    weight  size_M  size_XL  color_green  color_red  gender_male
0  1.845062  1.366002   False     True        False       True        False
1 -0.691898  0.623610   False    False         True      False         True
2 -0.461266 -1.603567    True    False        False      False         True
3  0.230633 -0.415740   False    False         True      False        False
4 -0.922531  0.029696    True    False        False       True        False
0    1
1    0
2    1
3    0
4    1
Name: bought, dtype: int64


Wyświetl 5 pierwszych wierszy obiektu _data_. Upewnij się, że nie ma w nim kolumny _bought_.

In [ ]:
# tutaj wpisz rozwiązanie
data.head()

price    weight  size_M  size_XL  color_green  color_red  gender_male
0  1.845062  1.366002   False     True        False       True        False
1 -0.691898  0.623610   False    False         True      False         True
2 -0.461266 -1.603567    True    False        False      False         True
3  0.230633 -0.415740   False    False         True      False        False
4 -0.922531  0.029696    True    False        False       True        False

Wyświetl 5 pierwszych wierszy obiektu _target_.

In [ ]:
# tutaj wpisz rozwiązanie
target.head()

0    1
1    0
2    1
3    0
4    1
Name: bought, dtype: int64

### <a name='8'></a> Ćwiczenie 198
Wykorzystując bibliotekę _scikit-learn_ oraz funkcję _train_test_split_ podziel dane z obiektów _data_ i _target_ na zbiór treningowy (_X\_train_, _y\_train_) oraz zbiór testowy (_X\_test_, _y\_test_). Do zbioru testowego przydziel 20% próbek.

Wyświetl rozmiar obiektów:
* _X\_train_
* _X\_test_
* _y\_train_
* _y\_test_

In [ ]:
# tutaj wpisz rozwiązanie
from sklearn.model_selection import train_test_split

# Podział danych na zbiór treningowy i testowy (test_size=0.2 oznacza 20% próbek w zbiorze testowym)
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=42)

# Wyświetlenie rozmiarów poszczególnych obiektów
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (4, 7)
X_test shape: (1, 7)
y_train shape: (4,)
y_test shape: (1,)


* Funkcja train_test_split dzieli dane na zbiory treningowy i testowy. Ustawienie parametru test_size=0.2 powoduje, że 20% próbek zostanie przydzielone do zbioru testowego.
* Parametr random_state=42 zapewnia, że podział danych będzie deterministyczny, co ułatwia powtarzalność wyników.
* X_train i X_test zawierają zmienne objaśniające (tutaj pozostałe cechy), a y_train i y_test odpowiadają za zmienną docelową target.
* Polecenie shape pozwala sprawdzić wymiary utworzonych zbiorów.

Przykładowo, jeśli oryginalny DataFrame zawiera 5 próbek, to zbiór treningowy będzie miał 4 próbki, a zbiór testowy 1 próbkę.

### <a name='9'></a> Ćwiczenie 199
Połącz obiekty _X\_train_ oraz _X\_test_ w jeden obiekt _DataFrame_ o nazwie _X_.

In [ ]:
# tutaj wpisz rozwiązanie

# Łączenie obiektów X_train oraz X_test w jeden DataFrame o nazwie X
X = pd.concat([X_train, X_test])

# Wyświetlenie wyniku
print(X)

      price    weight  size_M  size_XL  color_green  color_red  gender_male
4 -0.922531  0.029696    True    False        False       True        False
2 -0.461266 -1.603567    True    False        False      False         True
0  1.845062  1.366002   False     True        False       True        False
3  0.230633 -0.415740   False    False         True      False        False
1 -0.691898  0.623610   False    False         True      False         True


#### Kolumny kategoryczne (po zakodowaniu metodą get_dummies() z drop_first=True):

1. size_M i size_XL: Oryginalna kolumna size została zakodowana jako zmienne dummy. Przyjmując, że kategorie sortowane leksykograficznie to np. ["L", "M", "XL"] i pomijamy pierwszą ("L"),:
* Jeśli size_M jest True (a size_XL False), to dana obserwacja pochodzi z kategorii "M".
* Jeśli size_XL jest True (a size_M False), to dana obserwacja pochodzi z kategorii "XL".
* Jeśli obie są False, oznacza to, że dana obserwacja należy do kategorii "L" (pominiętej).
2. color_green i color_red: Podobnie oryginalna zmienna color została zakodowana. Zakładając sortowanie (np. ["blue", "green", "red"]) i pominięcie "blue":
* color_green ustawione na True oznacza kolor "green".
* color_red ustawione na True oznacza kolor "red".
* Jeśli obie są False, to kolor to "blue".
3. gender_male: Dla kolumny gender, przyjmując, że kategorie to ["female", "male"] i "female" została pominięta, wartość True oznacza "male", a False – "female".

### <a name='10'></a> Ćwiczenie 200
Połącz obiekty _y\_train_ oraz _y\_test_ w jeden obiekt _DataFrame_ o nazwie _y_.

In [ ]:
# tutaj wpisz rozwiązanie
y = pd.concat([y_train, y_test])
y

4    1
2    1
0    1
3    0
1    0
Name: bought, dtype: int64

Połącz obiekty _X_ oraz _y_ w jeden obiekt _DataFrame_.

In [ ]:
# tutaj wpisz rozwiązanie

# Łączymy X oraz y w jeden DataFrame (łączenie wzdłuż osi kolumn, axis=1)
df_combined = pd.concat([X, y], axis=1)

# Wyświetlenie wynikowego DataFrame
print(df_combined)

      price    weight  size_M  size_XL  color_green  color_red  gender_male  \
4 -0.922531  0.029696    True    False        False       True        False   
2 -0.461266 -1.603567    True    False        False      False         True   
0  1.845062  1.366002   False     True        False       True        False   
3  0.230633 -0.415740   False    False         True      False        False   
1 -0.691898  0.623610   False    False         True      False         True   

   bought  
4       1  
2       1  
0       1  
3       0  
1       0  


1. Używamy funkcji pd.concat() z argumentem axis=1, aby połączyć DataFrame X z Series y kolumnami. W rezultacie uzyskujemy DataFrame, w którym znajdują się wszystkie cechy oraz kolumna z wartością zmiennej docelowej.